server:
  port: 18761

spring:
  application:
    name: eureka
  profiles: slave1

eureka:
  instance:
    # 服务所在主机（一般都是配置域名）；本地测试的话，需要在 host 文件中指定虚拟域名
    hostname: 127.0.0.1
  client:
    service-url:
      # eureka服务器的地址
      defaultZone: http://127.0.0.1:28761/eureka
    # 获取注册列表
    fetch-registry: false
    # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息
    register-with-eureka: true



# 用连续三个连字号（---）区分多个文件（节省多个yml文件的配置，在一个yml文件中就可配置）。
---

#---------------------------------------------- eureka slave2 注册中心配置 ----------------------------------------------------
server:
  port: 28761

spring:
  application:
    name: eureka
  profiles: slave2

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      # eureka服务器的地址
      defaultZone: http://127.0.0.1:18761/eureka
    # 获取注册列表
    fetch-registry: false
    # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息
    register-with-eureka: true


